name: C++ CI

on:
  push:
    branches: [main, develop]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y g++ libgtest-dev cmake

    - name: Build GTest
      run: |
        sudo apt-get install -y googletest googletest-dev
        cd /usr/src/googletest
        sudo cmake -B build -S .
        sudo cmake --build build
        sudo cp build/lib/*.a /usr/lib

    - name: Compile and run tests
      run: |
        g++ -std=c++17 -IDateTime DateTime/DateTime.cpp DateTimeTests/DateTimeTests.cpp \
        -lgtest -lgtest_main -pthread -o tests
        ./tests
