name: C++ CI (No CMake)

on:
  push:
    branches: [main, develop]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y g++ libgtest-dev

    - name: Build GTest
      run: |
        cd /usr/src/gtest
        sudo cmake .
        sudo make
        sudo cp *.a /usr/lib

    - name: Compile and run tests
      run: |
        g++ -std=c++17 -IDateTime DateTime/DateTime.cpp 
DateTimeTests/DateTimeTests.cpp \
        -lgtest -lgtest_main -pthread -o tests
        ./tests
