name: C++ CI

on:
  push:
    branches: [main, develop]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y g++ libgtest-dev cmake

    - name: Build GTest
      run: |
        cd /usr/src/googletest || cd /usr/src/gtest
        sudo cmake -B build -S .
        sudo cmake --build build
        sudo cp build/lib/libgtest*.a /usr/lib

    - name: Compile and run tests
      run: |
        cd DateTime
        g++ -std=c++17 -I. DateTime.cpp DateTimeTests/Tests.cpp \
        -lgtest -lgtest_main -pthread -o tests
        ./tests
